2025-04-10 23:05:21,998 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-10 23:06:41,678 | INFO | django.utils.autoreload | D:\Django_api_jwt_logger\django_RestApi_project\tasks\views.py changed, reloading.
2025-04-10 23:06:43,281 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-10 23:07:27,096 | INFO | django.utils.autoreload | D:\Django_api_jwt_logger\django_RestApi_project\tasks\views.py changed, reloading.
2025-04-10 23:07:28,379 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-10 23:07:54,185 | INFO | django.utils.autoreload | D:\Django_api_jwt_logger\django_RestApi_project\tasks\views.py changed, reloading.
2025-04-10 23:07:55,500 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-10 23:08:01,450 | ERROR | custom | Exception occurred in  API call
Traceback (most recent call last):
  File "D:\Django_api_jwt_logger\django_RestApi_project\tasks\views.py", line 32, in taskCreate
    if serializer.isvalid():
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'TaskCreateSerializer' object has no attribute 'isvalid'
2025-04-10 23:08:01,515 | ERROR | django.server | "POST /api/task-create/ HTTP/1.1" 500 81750
2025-04-10 23:09:00,122 | INFO | django.utils.autoreload | D:\Django_api_jwt_logger\django_RestApi_project\tasks\views.py changed, reloading.
2025-04-10 23:09:01,557 | INFO | django.utils.autoreload | Watching for file changes with StatReloader
2025-04-10 23:09:03,598 | WARNING | django.server | "POST /api/task-create/ HTTP/1.1" 401 172
